### ISSUE TITLE
Expose Connect client for the gRPC reflection protocol

### ISSUE THREAD

**Issue by jhump** [bufbuild/connect-grpcreflect-go#41]
Trying to create a client that uses `connect-go` to communicate with a server that supports gRPC reflection is rather a hassle. Each such usage must use custom code generation (like this repo does) to avoid adding a dependency on `google.golang.org/grpc/reflection` (which would transitively bring in all of gRPC 😭). Given the name of this repo, it seems within bounds for this repo to provide that.

I know the API would want to avoid exposing the generated base types, for aesthetic reasons, but I don't think that's a very big lift. The only real question IMO is whether to drop it in the main `grpcreflect` package or to add a `grpcreflectclient` sub-package.

WDYT?

**Comment by akshayjshah** [comment]
Fine with me! I started exploring this, but I think I ran into some difficulty fully hiding the base types. If we can surmount that, let's do it.

If hiding the base types proves awkward or impossible, perhaps we could push the unmodified gRPC reflection schema to the BSR and direct people to use the generated Go packages from there?

**Comment by jhump** [comment]
> If hiding the base types proves awkward or impossible, perhaps we could push the unmodified gRPC reflection schema to the BSR and direct people to use the generated Go packages from there?

I was hesitant to go this route because a user's program could crash if they also happened to depend on (even if indirectly) the gRPC reflection package.

**Comment by akshayjshah** [comment]
> > If hiding the base types proves awkward or impossible, perhaps we could push the unmodified gRPC reflection schema to the BSR and direct people to use the generated Go packages from there?
> 
> I was hesitant to go this route because a user's program could crash if they also happened to depend on (even if indirectly) the gRPC reflection package.

Yeah. It's super painful that they just included generated code for this schema in the main gRPC module :/

**Comment by jhump** [comment]
This was added in #42.
